#!/usr/bin/env python3

from tokenizer import Tokenizer
from parser import Parser
from generator import Generator

# store file contents in variable, and tokenize it
fh = open("test.sql", "r")
code = " ".join(map(lambda x: x.strip(), fh.readlines()))
fh.close()

print("Tokens")
print("--------------------")
print()

tokens = Tokenizer(code).tokenize()
print(tokens)

print()
print()
print("Tree")
print("--------------------")
print()

trees = Parser(tokens).parse()
for tree in trees:
    print(tree)

print()
print()
print("Generated Code")
print("--------------------")
print()

generated_code = Generator().generate(tree)
print(generated_code)
