#!/usr/bin/env python3

from tokenizer import Tokenizer

# store file contents in variable, and tokenize it
fh = open("test.sql", "r")
code = " ".join(map(lambda x: x.strip(), fh.readlines()))
fh.close()

tokens = Tokenizer(code).tokenize()

print(tokens)
