#!/usr/bin/env python3

from tokenizer import Tokenizer
from parser import Parser
from generator import Generator

# store file contents in variable, and tokenize it
fh = open("test.sql", "r")
code = " ".join(map(lambda x: x.strip(), fh.readlines()))
fh.close()

tokens = Tokenizer(code).tokenize()

print(tokens)

print("--------------------")

tree = Parser(tokens).parse()

print(tree)

print("--------------------")

generated_code = Generator().generate(tree)

print(generated_code)
